spring:
  application:
    name: chronicle-api
#  config:
#    import: optional:file:.env[.properties]

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 30
      minimum-idle: 10

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      jdbc:
        batch_size: 5000
      hibernate:
        format_sql: true