services:
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chronicle
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G

  chronicle-api:
    build:
      context: .
      dockerfile: chronicle-api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATASOURCE_URL: jdbc:mysql://mysql:3306/chronicle?rewriteBatchedStatements=true
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          memory: 1G

#  chronicle-test-app-1:
#    build:
#      context: .
#      dockerfile: chronicle-test-app/Dockerfile
#    ports:
#      - "8081:8081"
#    environment:
#      SERVER_PORT: 8081
#      CHRONICLE_URL: http://chronicle-api:8080/v1/api/logs
#    depends_on:
#      - chronicle-api
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 1G
#
#  chronicle-test-app-2:
#    build:
#      context: .
#      dockerfile: chronicle-test-app/Dockerfile
#    ports:
#      - "8082:8082"
#    environment:
#      SERVER_PORT: 8082
#      CHRONICLE_URL: http://chronicle-api:8080/v1/api/logs
#    depends_on:
#      - chronicle-api
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 1G
#
#  chronicle-test-app-3:
#    build:
#      context: .
#      dockerfile: chronicle-test-app/Dockerfile
#    ports:
#      - "8083:8083"
#    environment:
#      SERVER_PORT: 8083
#      CHRONICLE_URL: http://chronicle-api:8080/v1/api/logs
#    depends_on:
#      - chronicle-api
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 1G
#
#  chronicle-test-app-4:
#    build:
#      context: .
#      dockerfile: chronicle-test-app/Dockerfile
#    ports:
#      - "8084:8084"
#    environment:
#      SERVER_PORT: 8084
#      CHRONICLE_URL: http://chronicle-api:8080/v1/api/logs
#    depends_on:
#      - chronicle-api
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 1G

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_MAX_BODY_SIZE=0

  grafana:
    image: grafana/grafana:11.6.10
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana:/var/lib/grafana

  k6:
    image: grafana/k6
    volumes:
      - ./k6:/scripts
    depends_on:
      - influxdb
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6

volumes:
  mysql_data:
  influxdb:
  grafana:
